version: '3'
services:
  server:
    container_name: docker-ts-mongo
    restart: always
    build: .
    ports: 
      - '6001:6001'
    links:
      - mongo
    environment:
      - PORT=6001
      - MONGO_URL=mongodb://mongo:27017/voting
  mongo:
    container_name: mongoDB
    image: mongo
    command: mongod --noauth --smallfiles
    ports:
      - '27017:27017'